networks:
  web:
    external: true

services:
  fish-web:
    build: .
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fish.rule=Host(`fish.tylergilman.com`)"
      - "traefik.http.routers.fish.entrypoints=websecure"
      - "traefik.http.routers.fish.tls.certresolver=leresolver"
      - "traefik.http.services.fish.loadbalancer.server.port=8000"
    environment:
      - LISTEN_ADDR=0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./:/app
